flags:
  synquid:
    synquid: true
packages:
  - '.'
resolver: lts-22.26
extra-deps:
  - z3-408.2
  - ansi-wl-pprint-0.6.9
# extra-include-dirs:
#  - <z3-home>/src/api
# extra-lib-dirs:
#  - <z3-home>/build
nix:
  # enable: true
  packages: [z3]
